# PR labeler rules

"breaking":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

"feature":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

"fix":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

"refactor":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

"docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "README.md"

"test":
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

"ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

"tooling":
  - changed-files:
      - any-glob-to-any-file:
          - "tools/**"

"chore":
  - changed-files:
      - any-glob-to-any-file:
          - "Directory.Build.props"
          - "Directory.Packages.props"
