// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FileTypeDetectionLib.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Dateityp_ErkennungUberInhaltsanalyseFail_ClosedFeature : object, global::Xunit.IClassFixture<Dateityp_ErkennungUberInhaltsanalyseFail_ClosedFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("de"), "Features", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "file_type_detection.feature"
#line hidden
        
        public Dateityp_ErkennungUberInhaltsanalyseFail_ClosedFeature(Dateityp_ErkennungUberInhaltsanalyseFail_ClosedFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
  #line hidden
#line 5
    await testRunner.GivenAsync("die Ressource \"sample.pdf\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 6
    await testRunner.AndAsync("die Ressource \"sample.jpg\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 7
    await testRunner.AndAsync("die Ressource \"sample.png\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 8
    await testRunner.AndAsync("die Ressource \"sample.gif\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 9
    await testRunner.AndAsync("die Ressource \"sample.webp\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 10
    await testRunner.AndAsync("die Ressource \"sample.zip\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 11
    await testRunner.AndAsync("die Ressource \"sample.docx\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 12
    await testRunner.AndAsync("die Ressource \"sample.xlsx\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 13
    await testRunner.AndAsync("die Ressource \"sample.pptx\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 14
    await testRunner.AndAsync("die Ressource \"sample_pdf_as_txt.txt\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 15
    await testRunner.AndAsync("die Ressource \"sample_pdf_no_extension\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 16
    await testRunner.AndAsync("die Ressource \"invalid_docx_marker_only.zip\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 17
    await testRunner.AndAsync("die Ressource \"invalid_xlsx_marker_only.zip\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 18
    await testRunner.AndAsync("die Ressource \"invalid_pptx_marker_only.zip\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 19
    await testRunner.AndAsync("die Ressource \"broken_no_ext\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 20
    await testRunner.AndAsync("die Ressource \"empty.bin\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 21
    await testRunner.AndAsync("die Ressource \"large_jpeg.bin\" existiert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/file_type_detection.feature.ndjson", 28);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Bekannte Signatur wird korrekt erkannt")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Bekannte Signatur wird korrekt erkannt")]
        [global::Xunit.InlineDataAttribute("sample.pdf", "Pdf", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("sample.jpg", "Jpeg", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("sample.png", "Png", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("sample.gif", "Gif", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("sample.webp", "Webp", "4", new string[0])]
        public async global::System.Threading.Tasks.Task BekannteSignaturWirdKorrektErkannt(string datei, string typ, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("datei", datei);
            argumentsOfScenario.Add("typ", typ);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bekannte Signatur wird korrekt erkannt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync(string.Format("die Datei \"{0}\"", datei), ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 25
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 26
    await testRunner.ThenAsync(string.Format("ist der erkannte Typ \"{0}\"", typ), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Kaputte Datei wird fail-closed als Unknown klassifiziert")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Kaputte Datei wird fail-closed als Unknown klassifiziert")]
        public async global::System.Threading.Tasks.Task KaputteDateiWirdFail_ClosedAlsUnknownKlassifiziert()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Kaputte Datei wird fail-closed als Unknown klassifiziert", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.GivenAsync("die Datei \"broken_no_ext\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 38
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 39
    await testRunner.ThenAsync("ist der erkannte Typ \"Unknown\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Leere Datei wird fail-closed als Unknown klassifiziert")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Leere Datei wird fail-closed als Unknown klassifiziert")]
        public async global::System.Threading.Tasks.Task LeereDateiWirdFail_ClosedAlsUnknownKlassifiziert()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Leere Datei wird fail-closed als Unknown klassifiziert", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.GivenAsync("die Datei \"empty.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 43
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 44
    await testRunner.ThenAsync("ist der erkannte Typ \"Unknown\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ZIP bleibt ZIP, wenn kein OOXML erkannt wird")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "ZIP bleibt ZIP, wenn kein OOXML erkannt wird")]
        public async global::System.Threading.Tasks.Task ZIPBleibtZIPWennKeinOOXMLErkanntWird()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ZIP bleibt ZIP, wenn kein OOXML erkannt wird", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 47
    await testRunner.GivenAsync("die Datei \"sample.zip\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 48
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 49
    await testRunner.ThenAsync("ist der erkannte Typ \"Zip\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="OOXML ZIP wird auf den konkreten Typ verfeinert")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "OOXML ZIP wird auf den konkreten Typ verfeinert")]
        [global::Xunit.InlineDataAttribute("sample.docx", "Docx", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("sample.xlsx", "Xlsx", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("sample.pptx", "Pptx", "10", new string[0])]
        public async global::System.Threading.Tasks.Task OOXMLZIPWirdAufDenKonkretenTypVerfeinert(string datei, string typ, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("datei", datei);
            argumentsOfScenario.Add("typ", typ);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("OOXML ZIP wird auf den konkreten Typ verfeinert", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 52
    await testRunner.GivenAsync(string.Format("die Datei \"{0}\"", datei), ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 53
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 54
    await testRunner.ThenAsync(string.Format("ist der erkannte Typ \"{0}\"", typ), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Marker-only ZIP wird nicht als OOXML verfeinert")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Marker-only ZIP wird nicht als OOXML verfeinert")]
        [global::Xunit.InlineDataAttribute("invalid_docx_marker_only.zip", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("invalid_xlsx_marker_only.zip", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("invalid_pptx_marker_only.zip", "13", new string[0])]
        public async global::System.Threading.Tasks.Task Marker_OnlyZIPWirdNichtAlsOOXMLVerfeinert(string datei, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("datei", datei);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker-only ZIP wird nicht als OOXML verfeinert", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync(string.Format("die Datei \"{0}\"", datei), ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 64
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 65
    await testRunner.ThenAsync("ist der erkannte Typ \"Zip\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Endungspruefung liefert fail-closed Unknown bei Mismatch")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Endungspruefung liefert fail-closed Unknown bei Mismatch")]
        public async global::System.Threading.Tasks.Task EndungspruefungLiefertFail_ClosedUnknownBeiMismatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Endungspruefung liefert fail-closed Unknown bei Mismatch", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 74
    await testRunner.GivenAsync("die Datei \"sample_pdf_as_txt.txt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 75
    await testRunner.WhenAsync("ich den Dateityp mit Endungspruefung ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 76
    await testRunner.ThenAsync("ist der erkannte Typ \"Unknown\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Endungspruefung liefert boolesches Ergebnis")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Endungspruefung liefert boolesches Ergebnis")]
        [global::Xunit.InlineDataAttribute("sample.pdf", "True", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("sample_pdf_as_txt.txt", "False", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("sample_pdf_no_extension", "True", "17", new string[0])]
        public async global::System.Threading.Tasks.Task EndungspruefungLiefertBooleschesErgebnis(string datei, string ergebnis, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("datei", datei);
            argumentsOfScenario.Add("ergebnis", ergebnis);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Endungspruefung liefert boolesches Ergebnis", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 79
    await testRunner.GivenAsync(string.Format("die Datei \"{0}\"", datei), ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 80
    await testRunner.WhenAsync("ich die Endung gegen den erkannten Typ pruefe", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 81
    await testRunner.ThenAsync(string.Format("ist das Endungsergebnis \"{0}\"", ergebnis), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Zu große Datei wird fail-closed als Unknown klassifiziert")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Zu große Datei wird fail-closed als Unknown klassifiziert")]
        public async global::System.Threading.Tasks.Task ZuGroBeDateiWirdFail_ClosedAlsUnknownKlassifiziert()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Zu große Datei wird fail-closed als Unknown klassifiziert", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 90
    await testRunner.GivenAsync("die maximale Dateigroesse ist 32 Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 91
    await testRunner.AndAsync("die Datei \"large_jpeg.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 92
    await testRunner.WhenAsync("ich den Dateityp ermittle", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 93
    await testRunner.ThenAsync("ist der erkannte Typ \"Unknown\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="MIME-Provider folgt dem Build-Toggle")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "MIME-Provider folgt dem Build-Toggle")]
        public async global::System.Threading.Tasks.Task MIME_ProviderFolgtDemBuild_Toggle()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("MIME-Provider folgt dem Build-Toggle", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 95
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 96
    await testRunner.ThenAsync("ist der MIME-Provider build-konform aktiv", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="ZIP-Entries werden extrahiert, als Bytes uebernommen und via FileMaterializer ges" +
            "peichert")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "ZIP-Entries werden extrahiert, als Bytes uebernommen und via FileMaterializer ges" +
            "peichert")]
        public async global::System.Threading.Tasks.Task ZIP_EntriesWerdenExtrahiertAlsBytesUebernommenUndViaFileMaterializerGespeichert()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ZIP-Entries werden extrahiert, als Bytes uebernommen und via FileMaterializer ges" +
                    "peichert", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 98
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 99
    await testRunner.GivenAsync("ein leeres temporäres Zielverzeichnis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 100
    await testRunner.AndAsync("die Datei \"sample.zip\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 101
    await testRunner.WhenAsync("ich extrahiere die ZIP-Datei sicher in Memory", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 102
    await testRunner.AndAsync("ich übernehme den ersten extrahierten Eintrag als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 103
    await testRunner.AndAsync("ich speichere die aktuellen Bytes als \"zip-entry-note.txt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 104
    await testRunner.ThenAsync("ist der extrahierte Eintragssatz nicht leer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
#line 105
    await testRunner.AndAsync("existiert die gespeicherte Datei \"zip-entry-note.txt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 106
    await testRunner.AndAsync("entspricht die gespeicherte Datei \"zip-entry-note.txt\" den aktuellen Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Originaldatei-Bytes werden iterativ gespeichert und als letzter Stand weiterverwe" +
            "ndet")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Originaldatei-Bytes werden iterativ gespeichert und als letzter Stand weiterverwe" +
            "ndet")]
        public async global::System.Threading.Tasks.Task Originaldatei_BytesWerdenIterativGespeichertUndAlsLetzterStandWeiterverwendet()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Originaldatei-Bytes werden iterativ gespeichert und als letzter Stand weiterverwe" +
                    "ndet", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 109
    await testRunner.GivenAsync("ein leeres temporäres Zielverzeichnis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 110
    await testRunner.AndAsync("ich lese die Datei \"sample.pdf\" als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 111
    await testRunner.WhenAsync("ich speichere die aktuellen Bytes als \"chain-original-step1.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 112
    await testRunner.AndAsync("ich lade die zuletzt gespeicherten Bytes als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 113
    await testRunner.AndAsync("ich speichere die aktuellen Bytes als \"chain-original-step2.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 114
    await testRunner.ThenAsync("existiert die gespeicherte Datei \"chain-original-step1.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
#line 115
    await testRunner.AndAsync("existiert die gespeicherte Datei \"chain-original-step2.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 116
    await testRunner.AndAsync("entspricht die gespeicherte Datei \"chain-original-step2.bin\" den aktuellen Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Extrahierte ZIP-Entry-Bytes werden iterativ gespeichert und als letzter Stand wei" +
            "terverwendet")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Extrahierte ZIP-Entry-Bytes werden iterativ gespeichert und als letzter Stand wei" +
            "terverwendet")]
        public async global::System.Threading.Tasks.Task ExtrahierteZIP_Entry_BytesWerdenIterativGespeichertUndAlsLetzterStandWeiterverwendet()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Extrahierte ZIP-Entry-Bytes werden iterativ gespeichert und als letzter Stand wei" +
                    "terverwendet", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 118
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 119
    await testRunner.GivenAsync("ein leeres temporäres Zielverzeichnis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 120
    await testRunner.AndAsync("die Datei \"sample.zip\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 121
    await testRunner.WhenAsync("ich extrahiere die ZIP-Datei sicher in Memory", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 122
    await testRunner.AndAsync("ich übernehme den ersten extrahierten Eintrag als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 123
    await testRunner.AndAsync("ich speichere die aktuellen Bytes als \"chain-zip-step1.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 124
    await testRunner.AndAsync("ich lade die zuletzt gespeicherten Bytes als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 125
    await testRunner.AndAsync("ich speichere die aktuellen Bytes als \"chain-zip-step2.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 126
    await testRunner.ThenAsync("ist der extrahierte Eintragssatz nicht leer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
#line 127
    await testRunner.AndAsync("existiert die gespeicherte Datei \"chain-zip-step1.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 128
    await testRunner.AndAsync("existiert die gespeicherte Datei \"chain-zip-step2.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 129
    await testRunner.AndAsync("entspricht die gespeicherte Datei \"chain-zip-step2.bin\" den aktuellen Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Materializer lehnt Speichern ohne overwrite bei bestehender Datei ab")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Materializer lehnt Speichern ohne overwrite bei bestehender Datei ab")]
        public async global::System.Threading.Tasks.Task MaterializerLehntSpeichernOhneOverwriteBeiBestehenderDateiAb()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Materializer lehnt Speichern ohne overwrite bei bestehender Datei ab", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 131
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 132
    await testRunner.GivenAsync("ein leeres temporäres Zielverzeichnis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 133
    await testRunner.AndAsync("es existiert bereits eine gespeicherte Datei \"conflict.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 134
    await testRunner.AndAsync("ich lese die Datei \"sample.pdf\" als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 135
    await testRunner.WhenAsync("ich versuche die aktuellen Bytes als \"conflict.bin\" ohne overwrite zu speichern", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 136
    await testRunner.ThenAsync("ist der letzte Speicherversuch fehlgeschlagen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
#line 137
    await testRunner.AndAsync("bleibt die bestehende Datei \"conflict.bin\" unveraendert", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Materializer lehnt ungueltigen Zielpfad ab")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Materializer lehnt ungueltigen Zielpfad ab")]
        public async global::System.Threading.Tasks.Task MaterializerLehntUngueltigenZielpfadAb()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Materializer lehnt ungueltigen Zielpfad ab", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 139
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 140
    await testRunner.GivenAsync("ich lese die Datei \"sample.pdf\" als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 141
    await testRunner.WhenAsync("ich versuche die aktuellen Bytes in den Zielpfad \"   \" zu speichern", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 142
    await testRunner.ThenAsync("ist der letzte Speicherversuch fehlgeschlagen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
#line 143
    await testRunner.AndAsync("existiert keine Datei im Zielpfad \"   \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Materializer lehnt zu grosse Payload gegen MaxBytes ab")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dateityp-Erkennung über Inhaltsanalyse (fail-closed)")]
        [global::Xunit.TraitAttribute("Description", "Materializer lehnt zu grosse Payload gegen MaxBytes ab")]
        public async global::System.Threading.Tasks.Task MaterializerLehntZuGrossePayloadGegenMaxBytesAb()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Materializer lehnt zu grosse Payload gegen MaxBytes ab", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 145
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 146
    await testRunner.GivenAsync("ein leeres temporäres Zielverzeichnis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Angenommen ");
#line hidden
#line 147
    await testRunner.AndAsync("die maximale Dateigroesse ist 16 Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 148
    await testRunner.AndAsync("ich lese die Datei \"sample.pdf\" als aktuelle Bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
#line 149
    await testRunner.WhenAsync("ich versuche die aktuellen Bytes als \"too-large.bin\" ohne overwrite zu speichern", ((string)(null)), ((global::Reqnroll.Table)(null)), "Wenn ");
#line hidden
#line 150
    await testRunner.ThenAsync("ist der letzte Speicherversuch fehlgeschlagen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dann ");
#line hidden
#line 151
    await testRunner.AndAsync("existiert die gespeicherte Datei \"too-large.bin\" nicht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Und ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Dateityp_ErkennungUberInhaltsanalyseFail_ClosedFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Dateityp_ErkennungUberInhaltsanalyseFail_ClosedFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
