#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORTABLE_DIR="${ROOT_DIR}/portable/FileTypeDetection"
WORK_DIR="/tmp/filetypedetection-portable-check"
CLEAN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workdir)
      WORK_DIR="${2:-}"
      shift 2
      ;;
    --clean)
      CLEAN=1
      shift
      ;;
    -h|--help)
      cat <<'USAGE'
Usage: ./tools/check-portable-filetypedetection.sh [--workdir <path>] [--clean]

Creates an isolated VB solution, copies portable FileTypeDetection sources,
restores/builds/runs once, and reports success/failure.

Options:
  --workdir <path>  Override temp directory (default: /tmp/filetypedetection-portable-check)
  --clean           Delete workdir after a successful run
USAGE
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ ! -d "${PORTABLE_DIR}" ]]; then
  echo "Portable directory not found: ${PORTABLE_DIR}" >&2
  exit 1
fi

if ! command -v dotnet >/dev/null 2>&1; then
  echo "dotnet is required but was not found in PATH." >&2
  exit 1
fi

TARGET_FRAMEWORK="$(grep -h -o '<TargetFramework>[^<]*' "${ROOT_DIR}"/src/*/*.csproj "${ROOT_DIR}"/src/*/*.vbproj 2>/dev/null | head -n 1 | sed 's/<TargetFramework>//')"
if [[ -z "${TARGET_FRAMEWORK}" ]]; then
  TARGET_FRAMEWORK="net10.0"
fi

echo "Preparing isolated check workspace: ${WORK_DIR}"
rm -rf "${WORK_DIR}"
mkdir -p "${WORK_DIR}"

pushd "${WORK_DIR}" >/dev/null

dotnet new sln -n PortableCheck >/dev/null
dotnet new console -lang VB -n PortableHost --framework "${TARGET_FRAMEWORK}" >/dev/null
SOLUTION_FILE="$(find . -maxdepth 1 -type f \( -name 'PortableCheck.sln' -o -name 'PortableCheck.slnx' \) | head -n 1)"
if [[ -z "${SOLUTION_FILE}" ]]; then
  echo "No solution file generated by 'dotnet new sln'." >&2
  exit 1
fi

dotnet sln "${SOLUTION_FILE}" add PortableHost/PortableHost.vbproj >/dev/null

mkdir -p PortableHost/FileTypeDetection
cp -R "${PORTABLE_DIR}/." PortableHost/FileTypeDetection/

cat > PortableHost/PortableHost.vbproj <<EOF
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>${TARGET_FRAMEWORK}</TargetFramework>
    <RootNamespace></RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageReference Include="Mime" Version="3.8.0" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
EOF

cat > PortableHost/Program.vb <<'EOF'
Option Strict On
Option Explicit On

Imports System
Imports FileTypeDetection

Module Program
    Sub Main(args As String())
        Dim detector As New FileTypeDetector()
        Dim detected = detector.Detect("does-not-exist.bin")
        Console.WriteLine(detected.Kind.ToString())
    End Sub
End Module
EOF

echo "Restoring..."
dotnet restore "${SOLUTION_FILE}" -v minimal

echo "Building..."
dotnet build "${SOLUTION_FILE}" -v minimal

echo "Running smoke check..."
dotnet run --project PortableHost/PortableHost.vbproj --no-build

popd >/dev/null

if [[ "${CLEAN}" == "1" ]]; then
  rm -rf "${WORK_DIR}"
  echo "Portable integration check passed. Workdir removed."
else
  echo "Portable integration check passed."
  echo "Workspace kept at: ${WORK_DIR}"
fi
